// Car Action Types
export const CAR_CREATE_REQUEST = "CAR_CREATE_REQUEST";
export const CAR_CREATE_SUCCESS = "CAR_CREATE_SUCCESS";
export const CAR_CREATE_FAILURE = "CAR_CREATE_FAILURE";

export const CAR_FETCH_ALL_REQUEST = "CAR_FETCH_ALL_REQUEST";
export const CAR_FETCH_ALL_SUCCESS = "CAR_FETCH_ALL_SUCCESS";
export const CAR_FETCH_ALL_FAILURE = "CAR_FETCH_ALL_FAILURE";

export const CAR_FETCH_BY_ID_REQUEST = "CAR_FETCH_BY_ID_REQUEST";
export const CAR_FETCH_BY_ID_SUCCESS = "CAR_FETCH_BY_ID_SUCCESS";
export const CAR_FETCH_BY_ID_FAILURE = "CAR_FETCH_BY_ID_FAILURE";

export const CAR_UPDATE_REQUEST = "CAR_UPDATE_REQUEST";
export const CAR_UPDATE_SUCCESS = "CAR_UPDATE_SUCCESS";
export const CAR_UPDATE_FAILURE = "CAR_UPDATE_FAILURE";

export const CAR_DELETE_REQUEST = "CAR_DELETE_REQUEST";
export const CAR_DELETE_SUCCESS = "CAR_DELETE_SUCCESS";
export const CAR_DELETE_FAILURE = "CAR_DELETE_FAILURE";

export const GET_CARS_BY_CATEGORY_REQUEST = 'GET_CARS_BY_CATEGORY_REQUEST';
export const GET_CARS_BY_CATEGORY_SUCCESS = 'GET_CARS_BY_CATEGORY_SUCCESS';
export const GET_CARS_BY_CATEGORY_FAILURE = 'GET_CARS_BY_CATEGORY_FAILURE';

