// Wedding Car Action Types
export const WEDDING_CAR_CREATE_REQUEST = "WEDDING_CAR_CREATE_REQUEST";
export const WEDDING_CAR_CREATE_SUCCESS = "WEDDING_CAR_CREATE_SUCCESS";
export const WEDDING_CAR_CREATE_FAILURE = "WEDDING_CAR_CREATE_FAILURE";

export const WEDDING_CAR_FETCH_ALL_REQUEST = "WEDDING_CAR_FETCH_ALL_REQUEST";
export const WEDDING_CAR_FETCH_ALL_SUCCESS = "WEDDING_CAR_FETCH_ALL_SUCCESS";
export const WEDDING_CAR_FETCH_ALL_FAILURE = "WEDDING_CAR_FETCH_ALL_FAILURE";

export const WEDDING_CAR_FETCH_BY_ID_REQUEST = "WEDDING_CAR_FETCH_BY_ID_REQUEST";
export const WEDDING_CAR_FETCH_BY_ID_SUCCESS = "WEDDING_CAR_FETCH_BY_ID_SUCCESS";
export const WEDDING_CAR_FETCH_BY_ID_FAILURE = "WEDDING_CAR_FETCH_BY_ID_FAILURE";

export const WEDDING_CAR_UPDATE_REQUEST = "WEDDING_CAR_UPDATE_REQUEST";
export const WEDDING_CAR_UPDATE_SUCCESS = "WEDDING_CAR_UPDATE_SUCCESS";
export const WEDDING_CAR_UPDATE_FAILURE = "WEDDING_CAR_UPDATE_FAILURE";

export const WEDDING_CAR_DELETE_REQUEST = "WEDDING_CAR_DELETE_REQUEST";
export const WEDDING_CAR_DELETE_SUCCESS = "WEDDING_CAR_DELETE_SUCCESS";
export const WEDDING_CAR_DELETE_FAILURE = "WEDDING_CAR_DELETE_FAILURE";
